language: python
python:
  - "3.7"
install:
  - pip install -U pip
  - pip install pytest-cov coveralls PyYAML
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --cov=brainrl
  - coveralls
