pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step:
          name: python3.9
          image: python:3.9
          script:
            - apt-get update -y && apt-get install -y swig
            - python3.9 -m pip install -U pip
            - python3.9 -m pip install pytest
            - python3.9 -m pip install -r requirements.txt
            - python3.9 -m pip install -e .
            - pytest
      - step:
          name: python3.7
          image: python:3.7
          script:
            - python3.7 -m pip install -U pip
            - python3.7 -m pip install pytest
            - python3.7 -m pip install -r requirements.txt
            - python3.7 -m pip install -e .
            - pytest
