image: python:3.7
pipelines:
  default:
    - step:
        script:
          - python3.7 -m pip install -r requirements.txt
          - python3.7 -m pip install -e .
          - python3.7 -m pip install pytest
          - pytest
