image: python:3.7

pipelines:
  default:
    - parallel:
      - step:
        name: Test
        caches:
          - pip
        script:
          - python3.7 -m pip install -r requirements.txt
          - python3.7 -m pip install .
          - python3.7 -m pip install pytest
          . pytest
