FROM python:3.7

# Install Python 3.7
RUN apt-get -y update && apt-get -y install swig

# Install library
ADD . /repo/
WORKDIR /repo/
RUN python3.7 -m pip -U pip
RUN python3.7 -m pip install -r requirements.txt
RUN python3.7 -m pip install -e .

VOLUME /repo
